version: '{build}'
skip_tags: true
image: Visual Studio 2017
#need set environment variable or it's not working in cache
#clone_script:
#  - if not exist %APPVEYOR_BUILD_FOLDER% (git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/craftwar/obs-deps.git)

environment:
  matrix:
    - favor_arch: INTEL64
      enable_nvenc: --enable-nvenc
    - favor_arch: AMD64
      enable_nvenc: --disable-nvenc

#  APPVEYOR_RDP_PASSWORD:
#    secure: K6XkhLVN7PZDnWWtrTKYneDPMS7FgBFYYe1xuU2s8js=
matrix:
  fast_finish: true

init:
  - ps: if (0) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) } #rdp debug
install:
  - call script\set_variable.cmd
  - mkdir "%pkg_prefix_win%\bin\" "%pkg_prefix_win%\include\" "%pkg_prefix_win%\lib\pkgconfig"
  - git submodule update --init --recursive --remote
  - ps: |
      $Env:release = Get-Date -UFormat "%Y-%m-%d / %A / %Z"
#  - call script\update_submodules.cmd
# use same as obs to prevent problem
#  - cd ffmpeg && git checkout ad56e8057d8af0201ed0cb65acc12e5889d4afcc
#  - cd %APPVEYOR_BUILD_FOLDER%\

  - C:\msys64\usr\bin\pacman -Syuu --needed --noconfirm
#  - C:\msys64\usr\bin\pacman -Su --noconfirm
  - C:\msys64\usr\bin\pacman -S --noconfirm mingw-w64-x86_64-nasm
  - C:\msys64\usr\bin\pacman -Q
#  - cmd
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set cl_options=-MP -Oi -arch:AVX2 -Gw -Gy -GL -favor:%favor_arch%
#  - set CL=/arch:AVX2
  - cd zlib
# LDFLAGS="-LTCG"  /LTCG is implied with /GL.
  - cmake -E env CFLAGS="%cl_options%" CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX="%pkg_prefix_win%" -DWITH_NATIVE_INSTRUCTIONS=true -DZLIB_COMPAT=true -DZLIB_ENABLE_TESTS=false
  - call msbuild /m /p:Configuration=Release zlib.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ..
#  - cmd
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\Release\zlib.lib" "%pkg_prefix_win%\lib\zlib.lib"
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\Release\zlib.exp" "%pkg_prefix_win%\lib\zlib.exp"
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\Release\zlib.dll" "%pkg_prefix_win%\bin\zlib.dll"
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\zlib.h" "%pkg_prefix_win%\include\zlib.h"
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\zconf.h" "%pkg_prefix_win%\include\zconf.h"
  - copy "%APPVEYOR_BUILD_FOLDER%\zlib\zlib.pc" "%pkg_prefix_win%\lib\pkgconfig\zlib.pc"

  - cd libpng
  - C:\msys64\usr\bin\bash.exe -lc "cd /c/projects/$APPVEYOR_PROJECT_NAME/libpng; git checkout `git tag -l 'v1.[0-9].[0-9][0-9]' | tail -1`"
  - set ZLIBLIB=%pkg_prefix_win%\lib
  - set ZLIBINC=%pkg_prefix_win%\include
  - set CPPFLAGS=-I%ZLIBINC%
  - set LDFLAGS=-L%ZLIBLIB%
  - set LD_LIBRARY_PATH=%ZLIBLIB%:%LD_LIBRARY_PATH%
  - cmake -E env CFLAGS="%cl_options%" CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" PNG_INTEL_SSE="yes" cmake . -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX=%pkg_prefix_win% -DPNG_TESTS=off -DPNG_SHARED=off
#  - cmd
  - call msbuild /m /p:Configuration=Release INSTALL.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ..

#unistd.h. This gets erroneously included when building FFmpeg (msvc)
# tell ffmpeg no this file (-DHAVE_UNISTD_H=0), not working...
  - C:\msys64\usr\bin\bash.exe -lc "sed -i '/include <unistd.h>/d' %pkg_prefix_mingw%/include/zconf.h"
  - cd %APPVEYOR_BUILD_FOLDER%\

build_script:
  - set MSYS2_PATH_TYPE=inherit
  - set MSYSTEM=MINGW64

  - C:\msys64\usr\bin\bash.exe -lc "cd /c/projects/$APPVEYOR_PROJECT_NAME/x264; CC=cl ./configure --extra-cflags='%cl_options%' --extra-ldflags='-LTCG' --prefix=\"$pkg_prefix_mingw\" --disable-cli --enable-shared --disable-interlaced --enable-lto; make -j install"
  - copy "%pkg_prefix_win%\lib\libx264.dll.lib" "%pkg_prefix_win%\lib\x264.lib"
  - copy "%pkg_prefix_win%\lib\libx264.dll.lib" "%pkg_prefix_win%\lib\libx264.lib"
#  - C:\msys64\usr\bin\bash.exe -lc "cp /c/msys64/mingw64/lib/pkgconfig/libpng*.pc $pkg_prefix_mingw/lib/pkgconfig"
  - C:\msys64\usr\bin\bash.exe -lc "cd /c/projects/$APPVEYOR_PROJECT_NAME/ffnvcodec; make install PREFIX=$pkg_prefix_mingw"
  - C:\msys64\usr\bin\bash.exe -lc "/c/projects/$APPVEYOR_PROJECT_NAME/script/ffmpeg_compile.sh"
  - cd "C:\projects\\%APPVEYOR_PROJECT_NAME%\packages\"
  - 7z a "C:\projects\\%APPVEYOR_PROJECT_NAME%"\VCdeps.7z -mx=9 -myx=9 "%pkg_prefix_win%"
  - cd ..
test: off
before_deploy:
  - ps: Push-AppveyorArtifact "VCdeps.7z" -FileName "VCdeps-${Env:favor_arch}.7z"
cache:
#  - C:\tools\vcpkg\installed\
#  - '%pkg_prefix_win% -> appveyor.yml'
#  - '%APPVEYOR_BUILD_FOLDER%' -> appveyor.yml
#  - ffmpeg -> appveyor.yml
#  - x264 -> appveyor.yml
deploy:
  - provider: GitHub
    tag: git
    release: $(release)
    description: Release title = build time
    auth_token:
      secure: KxeGOEgx0+XWdjLWDsyhC+B/w3m8zpvtVY/e+90lCLZgd/2VSuraPZDxdIPB5rfY
    force_update: true
    on:
      branch: master
